services:
  chainlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: chainlit run app.py

volumes:
  data:
    driver: local